version: "3.8"
services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
